// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHsPPznI_wO8_4PMbcgbu0MZGVNjc6Mw',
    appId: '1:928570607132:web:ba55317dcd63a4daf541d9',
    messagingSenderId: '928570607132',
    projectId: 'office-throne-app',
    authDomain: 'office-throne-app.firebaseapp.com',
    storageBucket: 'office-throne-app.firebasestorage.app',
    measurementId: 'G-C9R8J722W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTo1sX04K1hZB8J-DEdko0JjHM0QOngI',
    appId: '1:928570607132:android:d814aa41df3405e6f541d9',
    messagingSenderId: '928570607132',
    projectId: 'office-throne-app',
    storageBucket: 'office-throne-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Oqks38oMxQQkVwAdMwU1utSA_7cyCqE',
    appId: '1:928570607132:ios:6f5036da76c121eaf541d9',
    messagingSenderId: '928570607132',
    projectId: 'office-throne-app',
    storageBucket: 'office-throne-app.firebasestorage.app',
    iosBundleId: 'com.example.officeThrone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Oqks38oMxQQkVwAdMwU1utSA_7cyCqE',
    appId: '1:928570607132:ios:6f5036da76c121eaf541d9',
    messagingSenderId: '928570607132',
    projectId: 'office-throne-app',
    storageBucket: 'office-throne-app.firebasestorage.app',
    iosBundleId: 'com.example.officeThrone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIHsPPznI_wO8_4PMbcgbu0MZGVNjc6Mw',
    appId: '1:928570607132:web:f6e38fb691dbf7d5f541d9',
    messagingSenderId: '928570607132',
    projectId: 'office-throne-app',
    authDomain: 'office-throne-app.firebaseapp.com',
    storageBucket: 'office-throne-app.firebasestorage.app',
    measurementId: 'G-VT0QXWCND0',
  );
}
